azhou - Personal Schedule Default Quarter Fix
ucsb-cs156-f23/proj-courses-f23-7pm-4 pull request #26
Opened 2023-11-21 02:12 UTC by apzhou0

In this PR, we fix the issue of personal schedule creation failing before the quarter field is changed. 

Dokku Link: https://proj-courses-apzhou0-dev.dokku-12.cs.ucsb.edu/

To test, click on the link above and log in. Click on "Personal Schedules," select "Add Schedule," and enter a name and description but click "create" without changing the quarter. No errors should appear.

Storybook Link: 
 
Closes #11

2023-11-21 22:04 UTC, alicezhong1 approved these changes
LGTM, clear instructions and works on the dokku link

2023-11-21 23:40 UTC, chriscerie commented on frontend/src/main/components/Quarters/SingleQuarterDropdown.js
> +  }
React components must be pure as a rule and cannot have side effects during render. I would instead investigate why the fallback value in the useState is not working as intended. My suspicion is that the useState there isn't needed at all since the parent component is passing the same data down, and splitting source of truth like that is what causes these types of out of sync bugs.
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/8fada0ee857acaa0e54912feb2e2cead08e61f92/frontend/src/main/components/Jobs/UpdateCoursesByQuarterJobForm.js#L42

2023-11-22 03:54 UTC, apzhou0 commented on frontend/src/main/components/Quarters/SingleQuarterDropdown.js
> +  }
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/8fada0ee857acaa0e54912feb2e2cead08e61f92/frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js#L39

Am I supposed to change this line so that it doesn't take the quarter from localStorage? I looked through the other files and did not see any place where the quarter value in localStorage is set to some default value, so I assumed that I would have to do that in SingleQuarterDropdown.js

2023-11-22 04:29 UTC, chriscerie commented on frontend/src/main/components/Quarters/SingleQuarterDropdown.js
> +  }
In this case this state gets initialized with a fallback value, but localstorage falls behind.
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/256dcca6dbcba7bc986604d08699f6ce2eb8e0e4/frontend/src/main/components/Quarters/SingleQuarterDropdown.js#L28-L31

The bug is the form reads the localstorage value (which is behind) over the react state. localstorage never syncs with the react state until the field is changed.
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/256dcca6dbcba7bc986604d08699f6ce2eb8e0e4/frontend/src/main/components/Quarters/SingleQuarterDropdown.js#L35

This just goes to show the danger of splitting source of truth into duplicate states. The easiest way fix the issue is to implement the same fallback logic in the send function
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/8fada0ee857acaa0e54912feb2e2cead08e61f92/frontend/src/main/pages/PersonalSchedules/PersonalSchedulesCreatePage.js#L39

...but there's still an issue of duplicate state which harms readability. A better (but more involved) approach is to
* define the selected quarter state in the `PersonalSchedulesCreatePage`
* sync localstorage with it with `useEffect`
* change the onSubmit to read from the react state
* pass the created state and its setter down to `SingleQuarterDropdown` and remove these two unnecessary states
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/8fada0ee857acaa0e54912feb2e2cead08e61f92/frontend/src/main/components/PersonalSchedules/PersonalScheduleForm.js#L31-L35
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/256dcca6dbcba7bc986604d08699f6ce2eb8e0e4/frontend/src/main/components/Quarters/SingleQuarterDropdown.js#L28-L31
* ensure the new state in gets updated by `SingleQuarterDropdown`, so this except reference the new state setter
https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/blob/256dcca6dbcba7bc986604d08699f6ce2eb8e0e4/frontend/src/main/components/Quarters/SingleQuarterDropdown.js#L36

Either approach is fine. The 1st one will be easy but won't fix the root of the issue.

2023-11-22 17:52 UTC, apzhou0 commented on frontend/src/main/components/Quarters/SingleQuarterDropdown.js
> +  }
Thank you!

2023-11-23 21:29 UTC, EricM5 approved these changes

2023-11-24 16:17 UTC, pconrad commented
So, the dokku deployment still seems to have the bug for me:

![code-review](https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/assets/1119017/07c7ec9d-7ead-4b05-8209-537861c5b36f)

2023-11-24 16:20 UTC, pconrad requested changes
For me, it doesn't seem to have fixed the bug.

@chriscerie also makes some good suggestions about implementation. You may want to create a separate branch and try his approach. If it fixes the problem you can make a separate PR and close this one.

In any case, whether this approach, or the alternative, we need something that actually fixes the bug.

2023-11-24 18:15 UTC, chriscerie commented
Please, still address the review in https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/26#discussion_r1401336976. It might technically work now, but it still breaks react’s purity rule. Best case scenario it sets a bad precedent, worst case it causes a bug that will be very* difficult to find the root cause.

2023-11-25 19:55 UTC, pconrad approved these changes
LGTM

2023-11-25 20:02 UTC, merged