Fix Bug 'Search by Instructor's '+' button in table does nothing'
ucsb-cs156-f23/proj-courses-f23-7pm-4 pull request #31
Opened 2023-11-24 00:37 UTC by EricM5

Fixed bug.

When on Search By Instructor page, I pass in a new attribute (to a prop) to tell the table which page that is sending the form. If the page field == 'CourseOverTimeInstructor', then the table will omit the options to display the '+' and '-', eliminating the dropdown option.

After Edit:

<img width="1130" alt="image" src="https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/assets/76453820/d80d0340-9296-429f-89a3-7a09672e2d1b">

closes #2

2023-11-24 06:13 UTC, apzhou0 approved these changes
LGTM

2023-11-24 13:41 UTC, chriscerie commented on frontend/src/main/components/Sections/SectionsTable.js
> +export default function SectionsTable(props) {
Why change this? Destructuring props is much more readable because you can immediately see what props the component accepts. Without it, you’d need to look at the component definition.

2023-11-24 13:41 UTC, chriscerie commented on frontend/src/main/components/SectionsTableBase.js
> +  page,
It’s not immediately clear to readers what `page` actually does. Initially I thought you were adding pagination to the table. A more idiomatic approach to this would be along the lines of a `canExpand` prop.

Also, this approach omits expand for all rows, even for rows that have the same instructor teaching the section. Is that actually what you want? Perhaps a less brittle approach is to investigate why the existing check for `row.subRows.length` is not working as intended.

2023-11-24 16:32 UTC, pconrad requested changes
I have a few suggestions that are in alignment with @chriscerie 's suggesitons

2023-11-24 16:32 UTC, pconrad commented on frontend/src/main/components/Sections/SectionsTable.js
> +export default function SectionsTable(props) {
```suggestion
export default function SectionsTable({sections, canExpand=true}) {
```

If, instead, we make this a prop that describes the functionality and has a default value of the old behavior, then it will be backwards compatible with existing components, and easy to use the alternative behavior in future components.

2023-11-24 16:32 UTC, pconrad commented on frontend/src/tests/components/SectionsTableBase.test.js
> +        page="CourseOverTimeInstructor"
```suggestion
        canExpand={false}
```

2023-11-25 03:06 UTC, apzhou0 approved these changes
LGTM

2023-11-25 19:56 UTC, pconrad approved these changes
LGTM!

2023-11-25 20:07 UTC, merged