azhou - Course Details Button
ucsb-cs156-f23/proj-courses-f23-7pm-4 pull request #46
Opened 2023-11-27 05:38 UTC by apzhou0

2023-11-27 10:43 UTC, audoreven approved these changes
LGTM!

2023-11-27 22:26 UTC, EricM5 approved these changes
LGTM

2023-11-28 00:24 UTC, pconrad requested changes
There is a bug that needs to  be fixed: if you do a course search without being logged in, the course details button doesn't work.  But it should.

I think the only thing you need to do in order to fix this is to move this code in `App.js`
```jsx
  <Route
              exact
              path="/coursedetails/:yyyyq/:enrollCd"
              element={<CourseDetailsPage />}
            />
```

Move it out of the block that's guarded by:

```
  {hasRole(currentUser, "ROLE_USER") && (
``` 

And into the group at the bottom, the routes that are available even when you are not logged in.

I think that should fix it.   Give it a try.

2023-11-28 00:25 UTC, pconrad commented on frontend/src/main/components/Sections/SectionsTable.js
>    // Stryker enable all
This line should never have been allowed to be approved in this file.  Please remove it; it is unnecessary.  Stryker is enabled by default.

2023-11-28 00:28 UTC, pconrad requested changes
Several issues to take a look at.

2023-11-28 00:28 UTC, pconrad commented on frontend/src/main/components/Sections/SectionsTable.js
>    // Stryker disable BooleanLiteral
This line should never have been allowed to be in this file; it is likely to cover up a number of real testing issues.  Please remove it.  If that results in mutants that survive, we can look at whether to use a more surgical approach to a stryker exception, or just add the tests that are needed.

2023-11-28 00:28 UTC, pconrad commented on frontend/src/main/components/Sections/SectionsTable.js
>    // Stryker disable BooleanLiteral
```suggestion

```

2023-11-28 00:28 UTC, pconrad commented on frontend/src/main/components/Sections/SectionsTable.js
>    // Stryker enable all
```suggestion

```

2023-11-28 00:28 UTC, pconrad commented on frontend/src/main/pages/CourseDetails/CourseDetailsPage.js
> +    // Stryker disable all : hard to test for query caching
This needs a matching `// Stryker restore all`

2023-11-28 00:28 UTC, pconrad commented on frontend/src/main/pages/CourseDetails/CourseDetailsPage.js
```suggestion
// Stryker restore all
```

2023-11-28 22:23 UTC, Bennyyyyy approved these changes
LGTM

2023-11-30 06:55 UTC, merged