BC - Added the endpoint for finalsInfo
ucsb-cs156-f23/proj-courses-f23-7pm-4 pull request #67
Opened 2023-11-28 19:17 UTC by Bennyyyyy

Finished part 2 of Finals Information
- Added the endpoint
- Tested and works when both inputs are in

![image](https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/assets/42486595/c4e493ba-2738-45da-aae3-5242260221c9)

Closes: #59

2023-11-28 22:00 UTC, anisavic approved these changes
LGTM

2023-11-30 18:45 UTC, GlassBricks requested changes

2023-11-30 18:45 UTC, GlassBricks commented on src/main/java/edu/ucsb/cs156/courses/controllers/FinalsInfoController.java
> +    // FinalsInfo finalsInfo = getFinalsInfo(quarter, enrollCd)
Is this commented out code supposed to be in this PR?

If you plan on "finishing" the functionality in a following PR, please state so (and you can then ignore this comment)

2023-11-30 20:30 UTC, Bennyyyyy commented
I removed the comments. The functionality is to be implemented later on.

2023-11-30 21:06 UTC, audoreven submitted a review, later dismissed
LGTM

2023-11-30 23:15 UTC, closed without merging