Azhu - Add New Section Number Column
ucsb-cs156-f23/proj-courses-f23-7pm-4 pull request #74
Opened 2023-11-29 05:21 UTC by audoreven

We add a new column called Section Number which helps show whether the class is a section or not (XX00 -> Lecture, otherwise it is a section). This way it is clearer whether the class is a section or a lecture. 

![image](https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/assets/41387003/b9fa5d1e-e1fa-469e-868f-48a256ec3c3a)

Closes #9 

Same changes as https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/57#issue-2013372139, but some how CI/CD was failing on files that were not changed.

2023-11-29 06:48 UTC, Bennyyyyy approved these changes, later dismissed
LGTM

2023-11-30 18:38 UTC, GlassBricks commented
LGTM; remember to resolve merge conflicts

2023-11-30 18:38 UTC, GlassBricks submitted a review, later dismissed

2023-11-30 20:38 UTC, anisavic submitted a review, later dismissed
LGTM

2023-12-04 22:14 UTC, pconrad commented on frontend/src/main/pages/CourseOverTime/CourseOverTimeInstructorIndexPage.js
> +        <SectionsTable sections={courseJSON} />
Should we be removing this?   I have a sense that perhaps this was added for a reason in another PR.   Just check and make sure that this doesn't break something.

2023-12-04 22:19 UTC, pconrad requested changes
Please review the question below.

2023-12-04 23:19 UTC, audoreven commented on frontend/src/main/pages/CourseOverTime/CourseOverTimeInstructorIndexPage.js
> +        <SectionsTable sections={courseJSON} />
Thanks for catching that! Originally it was there to disable the drop-down function on the Search by Instructor page since it sometimes did not work. I don't think it's necessary for my bug fix to have the expand feature since adding a section number is sufficient to tell if the instructor is leading a primary section or not.

2023-12-05 17:12 UTC, pconrad approved these changes
LGTM

2023-12-05 17:13 UTC, merged